version: '3.5'

services:
  node:
    image: node:12
    container_name: mibh2-front
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    working_dir: /app
    command: tail -f /dev/null
    networks:
      - mibh2-network

networks:
  mibh2-network:
    external: true
